Temporarily revert to 4.8.0
4.5.4+ fail with
ImportError: cannot import name 'soft_unicode' from 'markupsafe'
This must be due to some other changes as it was working with an earlier version of this action